# TITANIC KAGGLE CHALLENGE

## My Work (more recent = closer to top)

### Loading the files (every section uses)

In [1]:
# KGAT_7f54eb9a13f74cf4dc43b6cf093a0949

import kagglehub

path = kagglehub.competition_download('titanic')
print("Path to competition files:", path)

C:\Users\rob22\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to competition files: C:\Users\rob22\.cache\kagglehub\competitions\titanic

In [2]:
import pandas as pd

In [3]:
train_data = pd.read_csv("C:/Users/rob22/.cache/kagglehub/competitions/titanic/train.csv")
test_data = pd.read_csv("C:/Users/rob22/.cache/kagglehub/competitions/titanic/test.csv")

### IMPROVED RF 3

In [4]:
train = train_data.copy()
test = test_data.copy()

train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
import numpy as np

train['Deck'] = train['Cabin'].apply(lambda x: str(x)[0] if pd.notnull(x) else 'U')
test['Deck'] = test['Cabin'].apply(lambda x: str(x)[0] if pd.notnull(x) else 'U')
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Deck
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,U
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,U
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,C
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,U

In [6]:
train['Deck'].unique()

<StringArray>
['U', 'C', 'E', 'G', 'D', 'A', 'B', 'F', 'T']
Length: 9, dtype: str

In [7]:
from sklearn.model_selection import train_test_split

# Deck T is only one specific cabin, belonging to a first class passenger. We can replace it with A, which is the most common first class cabin.
train['Deck'] = train['Deck'].replace('T', 'A')

y = train.Survived
features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Deck', 'Embarked']
X = pd.get_dummies(train[features])

test = pd.get_dummies(test[features])

train_X, val_X, train_y, val_y = train_test_split(X, y, random_state = 0)

In [8]:
X.head()

,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Deck_A,Deck_B,Deck_C,Deck_D,Deck_E,Deck_F,Deck_G,Deck_U,Embarked_C,Embarked_Q,Embarked_S
0,3,22.0,1,0,7.2500,False,True,False,False,False,False,False,False,False,True,False,False,True
1,1,38.0,1,0,71.2833,True,False,False,False,True,False,False,False,False,False,True,False,False
2,3,26.0,0,0,7.9250,True,False,False,False,False,False,False,False,False,True,False,False,True
3,1,35.0,1,0,53.1000,True,False,False,False,True,False,False,False,False,False,False,False,True
4,3,35.0,0,0,8.0500,False,True,False,False,False,False,False,False,False,True,False,False,True

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

model = RandomForestClassifier(n_estimators=1000, max_depth=6, min_samples_split=6, min_samples_leaf=2, random_state=1)
model.fit(train_X, train_y)
preds = model.predict(val_X)
print(accuracy_score(val_y, preds))

0.8116591928251121

In [10]:
model = RandomForestClassifier(n_estimators=1000, max_depth=6, min_samples_split=6, min_samples_leaf=2, random_state=1)
model.fit(X, y)
predictions = model.predict(test)

output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
output.to_csv('submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!

### IMPROVED RF 2 - minimal feature engineering + adding more params

In [91]:
train = train_data.copy()
test = test_data.copy()

train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [92]:
train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [93]:
from sklearn.model_selection import train_test_split

y = train.Survived
features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']
X = pd.get_dummies(train[features])

test = pd.get_dummies(test[features])

train_X, val_X, train_y, val_y = train_test_split(X, y, random_state = 0)

In [103]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

model = RandomForestClassifier(n_estimators=500, random_state=1)
model.fit(train_X, train_y)
preds = model.predict(val_X)
print(accuracy_score(val_y, preds))

0.8340807174887892

In [104]:
model.fit(X, y)
predictions = model.predict(test)

output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
output.to_csv('submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!

### IMPROVED RF - one hot encoding + more params

In [81]:
train = train_data.copy()
test = test_data.copy()

train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [82]:
from sklearn.model_selection import train_test_split

y = train.Survived
features = ['Pclass', 'Sex', 'Fare', 'Age', 'SibSp']
X = pd.get_dummies(train[features])

test = pd.get_dummies(test[features])

train_X, val_X, train_y, val_y = train_test_split(X, y, random_state = 0)

In [83]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

model = RandomForestClassifier(random_state=1)
model.fit(train_X, train_y)
preds = model.predict(val_X)
print(accuracy_score(val_y, preds))

0.8430493273542601

In [84]:
model.fit(X, y)
predictions = model.predict(test)

output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
output.to_csv('submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!

### Random Forest Classifier

In [75]:
train = train_data.copy()

train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [76]:
from sklearn.model_selection import train_test_split

y = train.Survived
features = ['Pclass', 'Fare', 'Age']
X = train[features]

train_X, val_X, train_y, val_y = train_test_split(X, y, random_state = 0)

In [77]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

model = RandomForestClassifier(random_state=1)
model.fit(train_X, train_y)
preds = model.predict(val_X)
print(accuracy_score(val_y, preds))

0.7354260089686099

In [78]:
model = RandomForestClassifier(random_state=1)
model.fit(X, y)

predictions = model.predict(test_data[features])

output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
output.to_csv('submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!

### Decision Tree Class w TTS and Best Model - accuracy score (leaf nodes)

In [64]:
train = train_data.copy()

train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [65]:
y = train.Survived

features = ['Pclass', 'Fare', 'Age']
X = train[features]

X.head()

   Pclass     Fare   Age
0       3   7.2500  22.0
1       1  71.2833  38.0
2       3   7.9250  26.0
3       1  53.1000  35.0
4       3   8.0500  35.0

In [67]:
from sklearn.model_selection import train_test_split

train_X, val_X, train_y, val_y = train_test_split(X, y, random_state = 0)

In [68]:
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

def get_accuracy(max_leaf_nodes, train_X, val_X, train_y, val_y):
    model = DecisionTreeClassifier(max_leaf_nodes=max_leaf_nodes, random_state=0)
    model.fit(train_X, train_y)
    preds_val = model.predict(val_X)
    accuracy = accuracy_score(val_y, preds_val)
    return(accuracy)

# mean absolute error - regression, accuracy score - classification

In [72]:
# compare MAE with differing values of max_leaf_nodes
for max_leaf_nodes in [5, 50, 500, 5000]:
    my_acc = get_accuracy(max_leaf_nodes, train_X, val_X, train_y, val_y)
    print("Max leaf nodes: %d  \t\t Accuracy:  %.4f" %(max_leaf_nodes, my_acc))

Max leaf nodes: 5  		 Accuracy:  0.6996
Max leaf nodes: 50  		 Accuracy:  0.7085
Max leaf nodes: 500  		 Accuracy:  0.6637
Max leaf nodes: 5000  		 Accuracy:  0.6637

In [73]:
best_model = DecisionTreeClassifier(max_leaf_nodes=50, random_state=0)
best_model.fit(X, y)

predictions = best_model.predict(test_data[features])

output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
output.to_csv('submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!

### Decision Tree Class w Train Test Split

In [41]:
train = train_data.copy()

train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [42]:
y = train.Survived

features = ['Pclass', 'Fare', 'Age']
X = train[features]

X.head()

   Pclass     Fare   Age
0       3   7.2500  22.0
1       1  71.2833  38.0
2       3   7.9250  26.0
3       1  53.1000  35.0
4       3   8.0500  35.0

In [43]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.tree import DecisionTreeClassifier

train_X, val_X, train_y, val_y = train_test_split(X, y, random_state = 0)

# The random_state argument guarantees we get the same split every time we run this script
model = DecisionTreeClassifier(random_state=1)

model.fit(train_X, train_y)

val_predictions = model.predict(val_X)
print(mean_absolute_error(val_y, val_predictions))

0.34977578475336324

In [44]:
predictions = model.predict(test_data[features])

output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
output.to_csv('submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!

### Decision Tree Classifier

In [ ]:
train = train_data.copy()

train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [33]:
y = train.Survived

features = ['Pclass', 'Fare', 'Age']
X = train[features]

X.head()

    Pclass     Fare   Age
1        1  71.2833  38.0
3        1  53.1000  35.0
6        1  51.8625  54.0
10       3  16.7000   4.0
11       1  26.5500  58.0

In [35]:
from sklearn.tree import DecisionTreeClassifier

# Specify a number for random_state to ensure same results each run
model = DecisionTreeClassifier(random_state=1)

model.fit(X, y)

DecisionTreeClassifier(random_state=1)

In [37]:
predictions = model.predict(test_data[features])

output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
output.to_csv('submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!

## Tutorial

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

# ------------------------------------------------------------------------

# KGAT_7f54eb9a13f74cf4dc43b6cf093a0949

import kagglehub

# Download latest version
path = kagglehub.competition_download('titanic')

print("Path to competition files:", path)

C:\Users\rob22\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\rob22\.cache\kagglehub\competitions\titanic.archive...

100%|██████████| 34.1k/34.1k [00:00<00:00, 34.8MB/s]

Extracting files...
Path to competition files: C:\Users\rob22\.cache\kagglehub\competitions\titanic

In [9]:
train_data = pd.read_csv("C:/Users/rob22/.cache/kagglehub/competitions/titanic/train.csv")
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [12]:
test_data = pd.read_csv("C:/Users/rob22/.cache/kagglehub/competitions/titanic/test.csv")
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [13]:
from sklearn.ensemble import RandomForestClassifier

y = train_data["Survived"]

features = ["Pclass", "Sex", "SibSp", "Parch"]
X = pd.get_dummies(train_data[features])
X_test = pd.get_dummies(test_data[features])

model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=1)
model.fit(X, y)
predictions = model.predict(X_test)

output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
output.to_csv('submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!

In [ ]:
# kaggle competitions submit -c titanic -f submission.csv  -m "Message"